package com.github.nhojpatrick.cucumber.testing.internal.objects.legacy;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.util.Map;

@BeanDefinition
@JsonAutoDetect(
        creatorVisibility = JsonAutoDetect.Visibility.NONE,
//        fieldVisibility = JsonAutoDetect.Visibility.DEFAULT,
        getterVisibility = JsonAutoDetect.Visibility.NONE,
        isGetterVisibility = JsonAutoDetect.Visibility.NONE,
        setterVisibility = JsonAutoDetect.Visibility.NONE
)
@JsonPropertyOrder({
        LegacyMyListComplexBottomObj.BRAVO
})
@SuppressFBWarnings(value = "CN_IDIOM_NO_SUPER_CALL", justification = "Managed by JodaBeans")
@SuppressWarnings("PMD.UselessParentheses")
public class LegacyMyListComplexBottomObj
        implements Bean,
        Cloneable {

    public static final String BRAVO = "bravo";

    @JsonProperty(BRAVO)
    @PropertyDefinition(set = "")
    private final String bravo;

    LegacyMyListComplexBottomObj() {
        this.bravo = null;
    }

    public LegacyMyListComplexBottomObj(final String bravo) {
        this.bravo = bravo;
    }

    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code LegacyMyListComplexBottomObj}.
     * @return the meta-bean, not null
     */
    public static LegacyMyListComplexBottomObj.Meta meta() {
        return LegacyMyListComplexBottomObj.Meta.INSTANCE;
    }

    static {
        MetaBean.register(LegacyMyListComplexBottomObj.Meta.INSTANCE);
    }

    @Override
    public LegacyMyListComplexBottomObj.Meta metaBean() {
        return LegacyMyListComplexBottomObj.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the bravo.
     * @return the value of the property
     */
    public String getBravo() {
        return bravo;
    }

    /**
     * Gets the the {@code bravo} property.
     * @return the property, not null
     */
    public final Property<String> bravo() {
        return metaBean().bravo().createProperty(this);
    }

    //-----------------------------------------------------------------------
    @Override
    public LegacyMyListComplexBottomObj clone() {
        return JodaBeanUtils.cloneAlways(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            LegacyMyListComplexBottomObj other = (LegacyMyListComplexBottomObj) obj;
            return JodaBeanUtils.equal(getBravo(), other.getBravo());
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash = hash * 31 + JodaBeanUtils.hashCode(getBravo());
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(64);
        buf.append("LegacyMyListComplexBottomObj{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
        buf.append("bravo").append('=').append(JodaBeanUtils.toString(getBravo())).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code LegacyMyListComplexBottomObj}.
     */
    public static class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code bravo} property.
         */
        private final MetaProperty<String> bravo = DirectMetaProperty.ofReadOnly(
                this, "bravo", LegacyMyListComplexBottomObj.class, String.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "bravo");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case 93998218:  // bravo
                    return bravo;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public BeanBuilder<? extends LegacyMyListComplexBottomObj> builder() {
            return new DirectBeanBuilder<>(new LegacyMyListComplexBottomObj());
        }

        @Override
        public Class<? extends LegacyMyListComplexBottomObj> beanType() {
            return LegacyMyListComplexBottomObj.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code bravo} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> bravo() {
            return bravo;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 93998218:  // bravo
                    return ((LegacyMyListComplexBottomObj) bean).getBravo();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 93998218:  // bravo
                    if (quiet) {
                        return;
                    }
                    throw new UnsupportedOperationException("Property cannot be written: bravo");
            }
            super.propertySet(bean, propertyName, newValue, quiet);
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------

}
