package com.github.nhojpatrick.cucumber.testing.internal.objects.legacy;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.util.Map;

@BeanDefinition
@JsonPropertyOrder({
        LegacyMySimpleObj.SIMPLE_NAME
})
@SuppressFBWarnings(value = "CN_IDIOM_NO_SUPER_CALL", justification = "Managed by JodaBeans")
@SuppressWarnings("PMD.UselessParentheses")
public class LegacyMySimpleObj
        implements Bean,
        Cloneable {

    public static final String SIMPLE_NAME = "simpleName";

    @JsonProperty(SIMPLE_NAME)
    @PropertyDefinition(set = "")
    private final String simpleName;

    LegacyMySimpleObj() {
        this.simpleName = null;
    }

    public LegacyMySimpleObj(final String simpleName) {
        this.simpleName = simpleName;
    }

    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code LegacyMySimpleObj}.
     * @return the meta-bean, not null
     */
    public static LegacyMySimpleObj.Meta meta() {
        return LegacyMySimpleObj.Meta.INSTANCE;
    }

    static {
        MetaBean.register(LegacyMySimpleObj.Meta.INSTANCE);
    }

    @Override
    public LegacyMySimpleObj.Meta metaBean() {
        return LegacyMySimpleObj.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the simpleName.
     * @return the value of the property
     */
    public String getSimpleName() {
        return simpleName;
    }

    /**
     * Gets the the {@code simpleName} property.
     * @return the property, not null
     */
    public final Property<String> simpleName() {
        return metaBean().simpleName().createProperty(this);
    }

    //-----------------------------------------------------------------------
    @Override
    public LegacyMySimpleObj clone() {
        return JodaBeanUtils.cloneAlways(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            LegacyMySimpleObj other = (LegacyMySimpleObj) obj;
            return JodaBeanUtils.equal(getSimpleName(), other.getSimpleName());
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash = hash * 31 + JodaBeanUtils.hashCode(getSimpleName());
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(64);
        buf.append("LegacyMySimpleObj{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
        buf.append("simpleName").append('=').append(JodaBeanUtils.toString(getSimpleName())).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code LegacyMySimpleObj}.
     */
    public static class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code simpleName} property.
         */
        private final MetaProperty<String> simpleName = DirectMetaProperty.ofReadOnly(
                this, "simpleName", LegacyMySimpleObj.class, String.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "simpleName");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case -1431767203:  // simpleName
                    return simpleName;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public BeanBuilder<? extends LegacyMySimpleObj> builder() {
            return new DirectBeanBuilder<>(new LegacyMySimpleObj());
        }

        @Override
        public Class<? extends LegacyMySimpleObj> beanType() {
            return LegacyMySimpleObj.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code simpleName} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> simpleName() {
            return simpleName;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case -1431767203:  // simpleName
                    return ((LegacyMySimpleObj) bean).getSimpleName();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            switch (propertyName.hashCode()) {
                case -1431767203:  // simpleName
                    if (quiet) {
                        return;
                    }
                    throw new UnsupportedOperationException("Property cannot be written: simpleName");
            }
            super.propertySet(bean, propertyName, newValue, quiet);
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------

}
