package com.github.nhojpatrick.cucumber.testing.internal.objects.legacy;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.util.List;
import java.util.Map;

@BeanDefinition
@JsonAutoDetect(
        creatorVisibility = JsonAutoDetect.Visibility.NONE,
//        fieldVisibility = JsonAutoDetect.Visibility.DEFAULT,
        getterVisibility = JsonAutoDetect.Visibility.NONE,
        isGetterVisibility = JsonAutoDetect.Visibility.NONE,
        setterVisibility = JsonAutoDetect.Visibility.NONE
)
@JsonPropertyOrder({
        LegacyMyNestedObj.BOTTOM,
        LegacyMyNestedObj.LABELS,
        LegacyMyNestedObj.NAME,
        LegacyMyNestedObj.NESTS
})
@SuppressFBWarnings(value = "CN_IDIOM_NO_SUPER_CALL", justification = "Managed by JodaBeans")
@SuppressWarnings("PMD.UselessParentheses")
public class LegacyMyNestedObj
        implements Bean,
        Cloneable {

    public static final String BOTTOM = "bottom";
    public static final String LABELS = "labels";
    public static final String NAME = "name";
    public static final String NESTS = "nests";

    @JsonProperty(NAME)
    @PropertyDefinition(set = "")
    private final String name;

    @JsonProperty(LABELS)
    @PropertyDefinition(set = "")
    private List<String> labels;

    @JsonProperty(BOTTOM)
    @PropertyDefinition(set = "")
    private final LegacyMyBottomObj bottom;

    @JsonProperty(NESTS)
    @PropertyDefinition(set = "")
    private final List<LegacyMyListNestedObj> nests;

    LegacyMyNestedObj() {
        this.name = null;
        this.labels = null;
        this.bottom = null;
        this.nests = null;
    }

    public LegacyMyNestedObj(final String name,
                             final List<String> labels,
                             final LegacyMyBottomObj bottom,
                             final List<LegacyMyListNestedObj> nests) {
        this.name = name;
        this.labels = labels;
        this.bottom = bottom;
        this.nests = nests;
    }

    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code LegacyMyNestedObj}.
     * @return the meta-bean, not null
     */
    public static LegacyMyNestedObj.Meta meta() {
        return LegacyMyNestedObj.Meta.INSTANCE;
    }

    static {
        MetaBean.register(LegacyMyNestedObj.Meta.INSTANCE);
    }

    @Override
    public LegacyMyNestedObj.Meta metaBean() {
        return LegacyMyNestedObj.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the name.
     * @return the value of the property
     */
    public String getName() {
        return name;
    }

    /**
     * Gets the the {@code name} property.
     * @return the property, not null
     */
    public final Property<String> name() {
        return metaBean().name().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the labels.
     * @return the value of the property
     */
    public List<String> getLabels() {
        return labels;
    }

    /**
     * Gets the the {@code labels} property.
     * @return the property, not null
     */
    public final Property<List<String>> labels() {
        return metaBean().labels().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the bottom.
     * @return the value of the property
     */
    public LegacyMyBottomObj getBottom() {
        return bottom;
    }

    /**
     * Gets the the {@code bottom} property.
     * @return the property, not null
     */
    public final Property<LegacyMyBottomObj> bottom() {
        return metaBean().bottom().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the nests.
     * @return the value of the property
     */
    public List<LegacyMyListNestedObj> getNests() {
        return nests;
    }

    /**
     * Gets the the {@code nests} property.
     * @return the property, not null
     */
    public final Property<List<LegacyMyListNestedObj>> nests() {
        return metaBean().nests().createProperty(this);
    }

    //-----------------------------------------------------------------------
    @Override
    public LegacyMyNestedObj clone() {
        return JodaBeanUtils.cloneAlways(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            LegacyMyNestedObj other = (LegacyMyNestedObj) obj;
            return JodaBeanUtils.equal(getName(), other.getName()) &&
                    JodaBeanUtils.equal(getLabels(), other.getLabels()) &&
                    JodaBeanUtils.equal(getBottom(), other.getBottom()) &&
                    JodaBeanUtils.equal(getNests(), other.getNests());
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash = hash * 31 + JodaBeanUtils.hashCode(getName());
        hash = hash * 31 + JodaBeanUtils.hashCode(getLabels());
        hash = hash * 31 + JodaBeanUtils.hashCode(getBottom());
        hash = hash * 31 + JodaBeanUtils.hashCode(getNests());
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(160);
        buf.append("LegacyMyNestedObj{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
        buf.append("name").append('=').append(JodaBeanUtils.toString(getName())).append(',').append(' ');
        buf.append("labels").append('=').append(JodaBeanUtils.toString(getLabels())).append(',').append(' ');
        buf.append("bottom").append('=').append(JodaBeanUtils.toString(getBottom())).append(',').append(' ');
        buf.append("nests").append('=').append(JodaBeanUtils.toString(getNests())).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code LegacyMyNestedObj}.
     */
    public static class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code name} property.
         */
        private final MetaProperty<String> name = DirectMetaProperty.ofReadOnly(
                this, "name", LegacyMyNestedObj.class, String.class);
        /**
         * The meta-property for the {@code labels} property.
         */
        @SuppressWarnings({"unchecked", "rawtypes" })
        private final MetaProperty<List<String>> labels = DirectMetaProperty.ofReadOnly(
                this, "labels", LegacyMyNestedObj.class, (Class) List.class);
        /**
         * The meta-property for the {@code bottom} property.
         */
        private final MetaProperty<LegacyMyBottomObj> bottom = DirectMetaProperty.ofReadOnly(
                this, "bottom", LegacyMyNestedObj.class, LegacyMyBottomObj.class);
        /**
         * The meta-property for the {@code nests} property.
         */
        @SuppressWarnings({"unchecked", "rawtypes" })
        private final MetaProperty<List<LegacyMyListNestedObj>> nests = DirectMetaProperty.ofReadOnly(
                this, "nests", LegacyMyNestedObj.class, (Class) List.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "name",
                "labels",
                "bottom",
                "nests");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case 3373707:  // name
                    return name;
                case -1110417409:  // labels
                    return labels;
                case -1383228885:  // bottom
                    return bottom;
                case 104710427:  // nests
                    return nests;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public BeanBuilder<? extends LegacyMyNestedObj> builder() {
            return new DirectBeanBuilder<>(new LegacyMyNestedObj());
        }

        @Override
        public Class<? extends LegacyMyNestedObj> beanType() {
            return LegacyMyNestedObj.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code name} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> name() {
            return name;
        }

        /**
         * The meta-property for the {@code labels} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<List<String>> labels() {
            return labels;
        }

        /**
         * The meta-property for the {@code bottom} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<LegacyMyBottomObj> bottom() {
            return bottom;
        }

        /**
         * The meta-property for the {@code nests} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<List<LegacyMyListNestedObj>> nests() {
            return nests;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 3373707:  // name
                    return ((LegacyMyNestedObj) bean).getName();
                case -1110417409:  // labels
                    return ((LegacyMyNestedObj) bean).getLabels();
                case -1383228885:  // bottom
                    return ((LegacyMyNestedObj) bean).getBottom();
                case 104710427:  // nests
                    return ((LegacyMyNestedObj) bean).getNests();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 3373707:  // name
                    if (quiet) {
                        return;
                    }
                    throw new UnsupportedOperationException("Property cannot be written: name");
                case -1110417409:  // labels
                    if (quiet) {
                        return;
                    }
                    throw new UnsupportedOperationException("Property cannot be written: labels");
                case -1383228885:  // bottom
                    if (quiet) {
                        return;
                    }
                    throw new UnsupportedOperationException("Property cannot be written: bottom");
                case 104710427:  // nests
                    if (quiet) {
                        return;
                    }
                    throw new UnsupportedOperationException("Property cannot be written: nests");
            }
            super.propertySet(bean, propertyName, newValue, quiet);
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------

}
