package com.github.nhojpatrick.cucumber.testing.internal.objects;

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.util.Map;

@BeanDefinition
@JsonCustomDefaults
@SuppressFBWarnings(value = {"CN_IDIOM_NO_SUPER_CALL",
        "EI_EXPOSE_REP",
        "USBR_UNNECESSARY_STORE_BEFORE_RETURN"},
        justification = "Managed by JodaBeans")
@SuppressWarnings("PMD.UselessParentheses")
public class BasicAttributesInnerObj
        implements Bean,
        Cloneable {

    public BasicAttributesInnerObj() {
    }

    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code BasicAttributesInnerObj}.
     * @return the meta-bean, not null
     */
    public static BasicAttributesInnerObj.Meta meta() {
        return BasicAttributesInnerObj.Meta.INSTANCE;
    }

    static {
        MetaBean.register(BasicAttributesInnerObj.Meta.INSTANCE);
    }

    @Override
    public BasicAttributesInnerObj.Meta metaBean() {
        return BasicAttributesInnerObj.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    @Override
    public BasicAttributesInnerObj clone() {
        return JodaBeanUtils.cloneAlways(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            return true;
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(32);
        buf.append("BasicAttributesInnerObj{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code BasicAttributesInnerObj}.
     */
    public static class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null);

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        public BeanBuilder<? extends BasicAttributesInnerObj> builder() {
            return new DirectBeanBuilder<>(new BasicAttributesInnerObj());
        }

        @Override
        public Class<? extends BasicAttributesInnerObj> beanType() {
            return BasicAttributesInnerObj.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
    }

    //-------------------------- AUTOGENERATED END --------------------------

}
