package com.github.nhojpatrick.cucumber.testing.internal.objects;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.util.Map;

@BeanDefinition
@JsonPropertyOrder({
        BasicArraysInnerObj.OBJECT_ARRAY_ID
})
@JsonAutoDetect(
        creatorVisibility = JsonAutoDetect.Visibility.NONE,
//        fieldVisibility = JsonAutoDetect.Visibility.DEFAULT,
        getterVisibility = JsonAutoDetect.Visibility.NONE,
        isGetterVisibility = JsonAutoDetect.Visibility.NONE,
        setterVisibility = JsonAutoDetect.Visibility.NONE
)
@SuppressFBWarnings(value = "CN_IDIOM_NO_SUPER_CALL", justification = "Managed by JodaBeans")
@SuppressWarnings("PMD.UselessParentheses")
public class BasicArraysInnerObj
        implements Bean,
        Cloneable {

    public static final String OBJECT_ARRAY_ID = "object_array_id";

    @JsonProperty(OBJECT_ARRAY_ID)
    @PropertyDefinition(set = "")
    private final String objectArrayId;

    BasicArraysInnerObj() {
        this.objectArrayId = null;
    }

    public BasicArraysInnerObj(final String objectArrayId) {
        this.objectArrayId = objectArrayId;
    }

    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code BasicArraysInnerObj}.
     * @return the meta-bean, not null
     */
    public static BasicArraysInnerObj.Meta meta() {
        return BasicArraysInnerObj.Meta.INSTANCE;
    }

    static {
        MetaBean.register(BasicArraysInnerObj.Meta.INSTANCE);
    }

    @Override
    public BasicArraysInnerObj.Meta metaBean() {
        return BasicArraysInnerObj.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the objectArrayId.
     * @return the value of the property
     */
    public String getObjectArrayId() {
        return objectArrayId;
    }

    /**
     * Gets the the {@code objectArrayId} property.
     * @return the property, not null
     */
    public final Property<String> objectArrayId() {
        return metaBean().objectArrayId().createProperty(this);
    }

    //-----------------------------------------------------------------------
    @Override
    public BasicArraysInnerObj clone() {
        return JodaBeanUtils.cloneAlways(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            BasicArraysInnerObj other = (BasicArraysInnerObj) obj;
            return JodaBeanUtils.equal(getObjectArrayId(), other.getObjectArrayId());
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash = hash * 31 + JodaBeanUtils.hashCode(getObjectArrayId());
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(64);
        buf.append("BasicArraysInnerObj{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
        buf.append("objectArrayId").append('=').append(JodaBeanUtils.toString(getObjectArrayId()))
                .append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code BasicArraysInnerObj}.
     */
    public static class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code objectArrayId} property.
         */
        private final MetaProperty<String> objectArrayId = DirectMetaProperty.ofReadOnly(
                this, "objectArrayId", BasicArraysInnerObj.class, String.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "objectArrayId");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case 74311957:  // objectArrayId
                    return objectArrayId;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public BeanBuilder<? extends BasicArraysInnerObj> builder() {
            return new DirectBeanBuilder<>(new BasicArraysInnerObj());
        }

        @Override
        public Class<? extends BasicArraysInnerObj> beanType() {
            return BasicArraysInnerObj.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code objectArrayId} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> objectArrayId() {
            return objectArrayId;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 74311957:  // objectArrayId
                    return ((BasicArraysInnerObj) bean).getObjectArrayId();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 74311957:  // objectArrayId
                    if (quiet) {
                        return;
                    }
                    throw new UnsupportedOperationException("Property cannot be written: objectArrayId");
            }
            super.propertySet(bean, propertyName, newValue, quiet);
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------

}
