package com.github.nhojpatrick.cucumber.json.testing.objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.util.Map;

@BeanDefinition
@SuppressFBWarnings(value = "CN_IDIOM_NO_SUPER_CALL", justification = "Managed by JodaBeans")
@SuppressWarnings("PMD.UselessParentheses")
public class MyListComplexBottomObj
        implements Bean,
        Cloneable {

    @JsonProperty
    @PropertyDefinition(set = "")
    private final String bravo;

    MyListComplexBottomObj() {
        this.bravo = null;
    }

    public MyListComplexBottomObj(final String bravo) {
        this.bravo = bravo;
    }

    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code MyListComplexBottomObj}.
     * @return the meta-bean, not null
     */
    public static MyListComplexBottomObj.Meta meta() {
        return MyListComplexBottomObj.Meta.INSTANCE;
    }

    static {
        MetaBean.register(MyListComplexBottomObj.Meta.INSTANCE);
    }

    @Override
    public MyListComplexBottomObj.Meta metaBean() {
        return MyListComplexBottomObj.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the bravo.
     * @return the value of the property
     */
    public String getBravo() {
        return bravo;
    }

    /**
     * Gets the the {@code bravo} property.
     * @return the property, not null
     */
    public final Property<String> bravo() {
        return metaBean().bravo().createProperty(this);
    }

    //-----------------------------------------------------------------------
    @Override
    public MyListComplexBottomObj clone() {
        return JodaBeanUtils.cloneAlways(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            MyListComplexBottomObj other = (MyListComplexBottomObj) obj;
            return JodaBeanUtils.equal(getBravo(), other.getBravo());
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash = hash * 31 + JodaBeanUtils.hashCode(getBravo());
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(64);
        buf.append("MyListComplexBottomObj{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
        buf.append("bravo").append('=').append(JodaBeanUtils.toString(getBravo())).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code MyListComplexBottomObj}.
     */
    public static class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code bravo} property.
         */
        private final MetaProperty<String> bravo = DirectMetaProperty.ofReadOnly(
                this, "bravo", MyListComplexBottomObj.class, String.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "bravo");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case 93998218:  // bravo
                    return bravo;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public BeanBuilder<? extends MyListComplexBottomObj> builder() {
            return new DirectBeanBuilder<>(new MyListComplexBottomObj());
        }

        @Override
        public Class<? extends MyListComplexBottomObj> beanType() {
            return MyListComplexBottomObj.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code bravo} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> bravo() {
            return bravo;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 93998218:  // bravo
                    return ((MyListComplexBottomObj) bean).getBravo();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 93998218:  // bravo
                    if (quiet) {
                        return;
                    }
                    throw new UnsupportedOperationException("Property cannot be written: bravo");
            }
            super.propertySet(bean, propertyName, newValue, quiet);
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------

}
