@Json
@Transformation
@Reverse
Feature: Transformation - Reverse - Checking with Specified keys


  @Success
  Scenario Outline: Reverse specifiedKeys transform complex input basic paths
    Given TestingInternalSteps I have setup the run state for keys and type:
      | object.key | ComplexObject |
    And I convert object using RunStateKey "object.key", to json map using RunStateKey "jsonMap.key"
    When I transform json map using RunStateKey "jsonMap.key" on paths:
      | path   | action  |
      | <path> | Reverse |
    Then I have run state key->value string pairs of:
      | jsonMap.key | <expected> |

    Examples:
      | path                            | expected                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | active                          | {count=3234, active=eurt, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]}              |
      | count                           | {count=4323, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]}              |
      | objs                            | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}]}              |
      | tags                            | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagThree, tagTwo, tagOne], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]}              |
      | title                           | {count=3234, active=true, title=xelpmoC, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]}              |
      | unknown1                        | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]}              |
      | unknown1.unknown2               | {count=3234, unknown1={}, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]} |

      | nested.labels                   | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelThree, labelTwo, labelOne], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]}              |
      | nested.name                     | {count=3234, active=true, title=Complex, nested={name=detseN, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]}              |
      | nested.nests                    | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]}              |
      | nested.unknown1                 | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]}              |
      | nested.unknown1.unknown2        | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}], unknown1={}}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]} |

      | nested.bottom.alpha             | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=ahplA}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]}              |
      | nested.bottom.unknown1          | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]}              |
      | nested.bottom.unknown1.unknown2 | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha, unknown1={}}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]} |


  @Error
  Scenario Outline: Reverse specifiedKeys transform complex input basic paths errors
    Given TestingInternalSteps I have setup the run state for keys and type:
      | object.key | ComplexObject |
    And I convert object using RunStateKey "object.key", to json map using RunStateKey "jsonMap.key"
    When TestingInternalSteps I transform json map using RunStateKey "jsonMap.key" and reverse the following path "<path>" produces the IllegalOperationException "<error>"
    # check run state has not changed
    And I have run state key->value string pairs of:
      | jsonMap.key | <expected> |

    Examples:
      | path                | error                                                         | expected                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
      | nested              | Unable to reverse JsonObject, at path 'nested'.               | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]} |
      | nested.bottom       | Unable to reverse JsonObject, at path 'nested.bottom'.        | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]} |
      | title.unknown       | Unable to convert primative to object, at path 'title'.       | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]} |
      | nested.name.unknown | Unable to convert primative to object, at path 'nested.name'. | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]} |


  @Success
  Scenario Outline: Complex input array <Object> paths
    Given TestingInternalSteps I have setup the run state for keys and type:
      | object.key | ComplexObject |
    And I convert object using RunStateKey "object.key", to json map using RunStateKey "jsonMap.key"
    When I transform json map using RunStateKey "jsonMap.key" on paths:
      | path   | action  |
      | <path> | Reverse |
    Then I have run state key->value string pairs of:
      | jsonMap.key | <expected> |

    Examples:
      | path              | expected                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
      | tags[0]           | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[enOgat, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]}                                                 |
      | tags[1]           | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, owTgat, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]}                                                 |
      | tags[2]           | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, eerhTgat], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]}                                                 |
      | tags[3]           | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree, null], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]}                                           |
      | tags[10]          | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree, null, null, null, null, null, null, null, null], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]} |

      | nested.labels[0]  | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[enOlebal, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]}                                                 |
      | nested.labels[1]  | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, owTlebal, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]}                                                 |
      | nested.labels[2]  | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, eerhTlebal], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]}                                                 |
      | nested.labels[3]  | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree, null], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]}                                           |
      | nested.labels[10] | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree, null, null, null, null, null, null, null, null], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]} |


  @Error
  Scenario Outline: Complex input array <Primative> paths errors
    Given TestingInternalSteps I have setup the run state for keys and type:
      | object.key | ComplexObject |
    And I convert object using RunStateKey "object.key", to json map using RunStateKey "jsonMap.key"
    When TestingInternalSteps I transform json map using RunStateKey "jsonMap.key" and reverse the following path "<path>" produces the IllegalOperationException "<error>"
    # check run state has not changed
    And I have run state key->value string pairs of:
      | jsonMap.key | <expected> |

    Examples:
      | path                     | error                                                                          | expected                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
      | tags[1].unknown          | Unable to convert primative array to object array, at path 'tags[1]'.          | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]} |
      | nested.labels[1].unknown | Unable to convert primative array to object array, at path 'nested.labels[1]'. | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]} |


  @Success
  Scenario Outline: Complex input array <String, Object> paths
    Given TestingInternalSteps I have setup the run state for keys and type:
      | object.key | ComplexObject |
    And I convert object using RunStateKey "object.key", to json map using RunStateKey "jsonMap.key"
    When I transform json map using RunStateKey "jsonMap.key" on paths:
      | path   | action  |
      | <path> | Reverse |
    Then I have run state key->value string pairs of:
      | jsonMap.key | <expected> |

    Examples:
      | path                             | expected                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
      #| objs[0]                          | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]}                                                      |
      #| objs[1]                          | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]}                                                      |
      #| objs[2]                          | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}]}                                                      |
      | objs[3]                          | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}, null]}                                           |
      | objs[10]                         | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}, null, null, null, null, null, null, null, null]} |

      | objs[1].lcId                     | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=4312, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]}                                                 |
      #| objs[1].lcBottom                 | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]}                              |
      | objs[1].lcBottom.bravo           | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=ovarB2sjbo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]}                                                 |

      #| nested.nests[0]                  | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]}                                                            |
      #| nested.nests[1]                  | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]}                                                            |
      #| nested.nests[2]                  | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]}                                                            |
      | nested.nests[3]                  | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}, null]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]}                                           |
      | nested.nests[10]                 | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}, null, null, null, null, null, null, null, null]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]} |

      | nested.nests[0].lnId             | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=3221, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]}                                                 |
      #| nested.nests[0].lnBottom         | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1234023}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]}                                   |
      | nested.nests[0].lnBottom.charlie | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=eilrahC1stsen}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]}                                                 |


  @Error
  Scenario Outline: Complex input array <Object> paths errors
    Given TestingInternalSteps I have setup the run state for keys and type:
      | object.key | ComplexObject |
    And I convert object using RunStateKey "object.key", to json map using RunStateKey "jsonMap.key"
    When TestingInternalSteps I transform json map using RunStateKey "jsonMap.key" and reverse the following path "<path>" produces the IllegalOperationException "<error>"
    # check run state has not changed
    And I have run state key->value string pairs of:
      | jsonMap.key | <expected> |

    Examples:
      | path                 | error                                                      | expected                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
      | objs.unknown         | Unable to convert array to object, at path 'objs'.         | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]} |
      | nested.nests.unknown | Unable to convert array to object, at path 'nested.nests'. | {count=3234, active=true, title=Complex, nested={name=Nested, labels=[labelOne, labelTwo, labelThree], bottom={alpha=Alpha}, nests=[{lnName=nests1, lnId=1223, lnBottom={charlie=nests1Charlie}}, {lnName=nests2, lnId=2234, lnBottom={charlie=nests2Charlie}}, {lnName=nests3, lnId=3245, lnBottom={charlie=nests3Charlie}}]}, tags=[tagOne, tagTwo, tagThree], objs=[{lcName=objs1, lcId=1123, lcBottom={bravo=objs1Bravo}}, {lcName=objs2, lcId=2134, lcBottom={bravo=objs2Bravo}}, {lcName=objs3, lcId=3145, lcBottom={bravo=objs3Bravo}}]} |
