@Json
@Transformation
@Remove
Feature: Transformation - Remove - Checking with Specified keys


  @Success
  Scenario Outline: Remove specifiedKeys transform complex input basic paths
    Given TestingInternalSteps I have setup the run state for keys and type:
      | object.key | ComplexObject |
    And I convert object using RunStateKey "object.key", to json map using RunStateKey "jsonMap.key"
    When I transform json map using RunStateKey "jsonMap.key" on paths:
      | path   | action |
      | <path> | Remove |
    Then I have run state key->value string pairs of:
      | jsonMap.key | <expected> |

    Examples:
      | path                            | expected                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | active                          | {count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex}                           |
      | count                           | {active=true, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex}                          |
      | nested                          | {active=true, count=3234, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex}                                                                                                                                                                                                                                                                                                     |
      | objs                            | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, tags=[tagOne, tagTwo, tagThree], title=Complex}                                                                                                                                                                                             |
      | tags                            | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], title=Complex}                                               |
      | title                           | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree]}                             |
      | unknown1                        | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex}              |
      | unknown1.unknown2               | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex, unknown1={}} |

      | nested.bottom                   | {active=true, count=3234, nested={labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex}                                    |
      | nested.labels                   | {active=true, count=3234, nested={bottom={alpha=Alpha}, name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex}                                                       |
      | nested.name                     | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex}                           |
      | nested.nests                    | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex}                                                                                                                                                                                                                |
      | nested.unknown1                 | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex}              |
      | nested.unknown1.unknown2        | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}], unknown1={}}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex} |

      | nested.bottom.alpha             | {active=true, count=3234, nested={bottom={}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex}                         |
      | nested.bottom.unknown1          | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex}              |
      | nested.bottom.unknown1.unknown2 | {active=true, count=3234, nested={bottom={alpha=Alpha, unknown1={}}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex} |


  @Error
  Scenario Outline: Remove specifiedKeys transform complex input basic paths errors
    Given TestingInternalSteps I have setup the run state for keys and type:
      | object.key | ComplexObject |
    And I convert object using RunStateKey "object.key", to json map using RunStateKey "jsonMap.key"
    When TestingInternalSteps I transform json map using RunStateKey "jsonMap.key" and remove the following path "<path>" produces the IllegalPathOperationException "<error>"
    # check run state has not changed
    And I have run state key->value string pairs of:
      | jsonMap.key | <expected> |

    Examples:
      | path                | error                                                         | expected                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
      | title.unknown       | Unable to convert primative to object, at path 'title'.       | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex} |
      | nested.name.unknown | Unable to convert primative to object, at path 'nested.name'. | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex} |


  @Success
  Scenario Outline: Complex input array <Object> paths
    Given TestingInternalSteps I have setup the run state for keys and type:
      | object.key | ComplexObject |
    And I convert object using RunStateKey "object.key", to json map using RunStateKey "jsonMap.key"
    When I transform json map using RunStateKey "jsonMap.key" on paths:
      | path   | action |
      | <path> | Remove |
    Then I have run state key->value string pairs of:
      | jsonMap.key | <expected> |

    Examples:
      | path              | expected                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
      | tags[0]           | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagTwo, tagThree], title=Complex}                                                   |
      | tags[1]           | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagThree], title=Complex}                                                   |
      | tags[2]           | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo], title=Complex}                                                     |
      | tags[3]           | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex}                                           |
      | tags[10]          | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree, null, null, null, null, null, null, null], title=Complex} |

      | nested.labels[0]  | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex}                                                     |
      | nested.labels[1]  | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex}                                                     |
      | nested.labels[2]  | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex}                                                       |
      | nested.labels[3]  | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex}                                           |
      | nested.labels[10] | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree, null, null, null, null, null, null, null], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex} |


  @Error
  Scenario Outline: Complex input array <Primative> paths errors
    Given TestingInternalSteps I have setup the run state for keys and type:
      | object.key | ComplexObject |
    And I convert object using RunStateKey "object.key", to json map using RunStateKey "jsonMap.key"
    When TestingInternalSteps I transform json map using RunStateKey "jsonMap.key" and remove the following path "<path>" produces the IllegalPathOperationException "<error>"
    # check run state has not changed
    And I have run state key->value string pairs of:
      | jsonMap.key | <expected> |

    Examples:
      | path                     | error                                                                       | expected                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
      | tags[1].unknown          | Unable to convert primative array to object array, at path 'tags'.          | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex} |
      | nested.labels[1].unknown | Unable to convert primative array to object array, at path 'nested.labels'. | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex} |


  @Success
  Scenario Outline: Complex input array <String, Object> paths
    Given TestingInternalSteps I have setup the run state for keys and type:
      | object.key | ComplexObject |
    And I convert object using RunStateKey "object.key", to json map using RunStateKey "jsonMap.key"
    When I transform json map using RunStateKey "jsonMap.key" on paths:
      | path   | action |
      | <path> | Remove |
    Then I have run state key->value string pairs of:
      | jsonMap.key | <expected> |

    Examples:
      | path                             | expected                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
      | objs[0]                          | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex}                                                                                                   |
      | objs[1]                          | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex}                                                                                                   |
      | objs[2]                          | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}], tags=[tagOne, tagTwo, tagThree], title=Complex}                                                                                                   |
      | objs[3]                          | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex}                                           |
      | objs[10]                         | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}, null, null, null, null, null, null, null], tags=[tagOne, tagTwo, tagThree], title=Complex} |

      | objs[1].lcBottom                 | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex}                                                                        |
      | objs[1].lcId                     | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex}                                                      |
      | objs[1].lcBottom.bravo           | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex}                                                           |

      | nested.nests[0]                  | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex}                                                                                                         |
      | nested.nests[1]                  | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex}                                                                                                         |
      | nested.nests[2]                  | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex}                                                                                                         |
      | nested.nests[3]                  | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex}                                           |
      | nested.nests[10]                 | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}, null, null, null, null, null, null, null]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex} |

      | nested.nests[0].lnBottom         | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex}                                                                             |
      | nested.nests[0].lnId             | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex}                                                      |
      | nested.nests[0].lnBottom.charlie | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex}                                                                |


  @Error
  Scenario Outline: Complex input array <Object> paths errors
    Given TestingInternalSteps I have setup the run state for keys and type:
      | object.key | ComplexObject |
    And I convert object using RunStateKey "object.key", to json map using RunStateKey "jsonMap.key"
    When TestingInternalSteps I transform json map using RunStateKey "jsonMap.key" and remove the following path "<path>" produces the IllegalPathOperationException "<error>"
    # check run state has not changed
    And I have run state key->value string pairs of:
      | jsonMap.key | <expected> |

    Examples:
      | path                 | error                                                      | expected                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
      | objs.unknown         | Unable to convert array to object, at path 'objs'.         | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex} |
      | nested.nests.unknown | Unable to convert array to object, at path 'nested.nests'. | {active=true, count=3234, nested={bottom={alpha=Alpha}, labels=[labelOne, labelTwo, labelThree], name=Nested, nests=[{lnBottom={charlie=nests1Charlie}, lnId=1223, lnName=nests1}, {lnBottom={charlie=nests2Charlie}, lnId=2234, lnName=nests2}, {lnBottom={charlie=nests3Charlie}, lnId=3245, lnName=nests3}]}, objs=[{lcBottom={bravo=objs1Bravo}, lcId=1123, lcName=objs1}, {lcBottom={bravo=objs2Bravo}, lcId=2134, lcName=objs2}, {lcBottom={bravo=objs3Bravo}, lcId=3145, lcName=objs3}], tags=[tagOne, tagTwo, tagThree], title=Complex} |
